### ISSUE TITLE
project5-zfr-submission

### ISSUE THREAD

**Issue by afek590** [afek590/Seniors-In-Touchnology#11]
@ItamarShDev

**Comment by robi-y** [comment]
- move US to backlog _ assign to MS
- upload some prototype to github
- add link to developer manual

**Comment by DorianTs** [comment]
היי @robi-y, ישבנו על הנקודות שרשמת לנו לתקן, אתה מוזמן להסתכל.

**Comment by robi-y** [comment]
Only 3 iterations?
Prototype section of ZFR should explain what was implemented/spikes by now
ZFR only need to link to developer documentation, it needs a better home, like in the main README

**Comment by afek590** [comment]
@robi-y 
סליחה על הבלבול, זה האישיו של ההגשה
בקשר להערות שכתבת לנו פה למעלה - אם אתה זוכר ישבנו איתך בכיתה באחת ההפסקות של ההרצאה וסידרנו את הבעיות ואמרת לנו שהציון יעלה
נשמח לדעת מדוע הציון עומד על 79?
תודה מראש.

**Comment by robi-y** [comment]
Sorry I can't restore it, so talk to me again..

**Comment by afek590** [comment]
@robi-y 
שלום ראובן
אמרת לנו בגיטר להגיב לך על האישיו על מנת לברר על הציון שקיבלנו.
קיבלנו ב ZFR 
ציון של 79 למרות שתיקנו את כל הליקויים שהערת לנו ובנוסף גם ישבנו איתך באופן אישי על סבב זה.
נשמח לדעת מדוע הציון שלנו עדיין יחסית נמוך.
תודה מראש.

**Comment by robi-y** [comment]
Already replied above.
Here we only discuss technical issue. For grading write to me by mail or set a meeting
