### ISSUE TITLE
Iteration 1 - MVP - Submission

### ISSUE THREAD

**Issue by afek590** [afek590/Seniors-In-Touchnology#20]
@ItamarShDev

**Comment by ItamarShDev** [comment]
:+1: 
what about code reviews and next iteration plans?

**Comment by afek590** [comment]
@ItamarShDev 
We did code reviews, like those for example:
- [Example 1](https://github.com/afek590/Seniors-In-Touchnology/commit/01207ce5685e768928e693b49a34626d65afcd50)
- [Example 2](https://github.com/afek590/Seniors-In-Touchnology/commit/c0c340654454a6c6fcbb746cd42c6ee32f5bff8a)

and there is more of course..

About next iteration plans, we did it on the issues
You can check the iteration plans on it's milestone - [Iteration 2](https://github.com/afek590/Seniors-In-Touchnology/milestones/Iteration%202) .

**Comment by ItamarShDev** [comment]
:+1:
