### ISSUE TITLE
Iteration 3 - DUI - Submission

### ISSUE THREAD

**Issue by afek590** [afek590/Seniors-In-Touchnology#24]
[Iteration 3](https://github.com/afek590/Seniors-In-Touchnology/wiki/3-DUI)

**Comment by afek590** [comment]
@ItamarShDev 
היי איתמר הוספנו פירוט באישיו של האיטרציה בנוגע לכל האלמנטים שהתעסקנו בהם בעיצוב האתר, כפי שביקשת.
[Issue](https://github.com/afek590/Seniors-In-Touchnology/issues/21)

**Comment by ItamarShDev** [comment]
:+1:
